# Generated by Django 4.2.18 on 2025-04-17 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pokemon_id', models.IntegerField(unique=True)),
                ('name', models.CharField(max_length=50)),
                ('image_url', models.URLField(blank=True, null=True)),
                ('types', models.CharField(max_length=100)),
            ],
        ),
    ]
