# Generated by Django 4.2.18 on 2025-04-26 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_useraccount_userpokemon_listing_delete_ownedpokemon'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpokemon',
            name='is_selling',
            field=models.BooleanField(default=False),
        ),
    ]
