# Generated by Django 5.0 on 2025-04-27 00:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_userpokemon_is_selling'),
        ('swap_house', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trade',
            name='offered_pokemon',
        ),
        migrations.RemoveField(
            model_name='tradeoffer',
            name='offered_pokemon',
        ),
        migrations.AddField(
            model_name='trade',
            name='offered_cards',
            field=models.ManyToManyField(related_name='trade_offers_in', to='accounts.userpokemon'),
        ),
        migrations.AddField(
            model_name='tradeoffer',
            name='offered_cards',
            field=models.ManyToManyField(related_name='offers_made', to='accounts.userpokemon'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_trades', to='accounts.useraccount'),
        ),
        migrations.AlterField(
            model_name='tradeoffer',
            name='offerer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='made_offers', to='accounts.useraccount'),
        ),
        migrations.AlterField(
            model_name='tradeoffer',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='pending', max_length=10),
        ),
    ]
